server:
  port: 8088
spring:
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 2695240777@qq.com #发送邮件的邮箱地址
    password:  dzccjyhfvvzqdfha #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 2695240777@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  datasource:
    #    url: jdbc:mysql://192.168.1.7/tfms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql:///tmsystem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

person:
  uname: 罗玺
  age: 10
  dog:
    dname: tom
    dtype: kk
  maps: {k1: v1,k2: v3}
  lists:
    - ss
    - s
    - ff




