server:
  port: 8088
spring:
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
    mode: HTML5 # 模板模式

person:
  uname: 罗玺
  age: 10
  dog:
    dname: tom
    dtype: kk
  maps: {k1: v1,k2: v3}
  lists:
    - ss
    - s
    - ff
